name: CDelivery

on:
  push:
    branches: [ main ]

jobs:
  security_hardening:
    name: Check security hardening
    runs-on: ubuntu-latest
    steps:
    - name: Clone the repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
    - name: Ensure SHA pinned actions
      uses: zgosalvez/github-actions-ensure-sha-pinned-actions@ca46236c6ce584ae24bc6283ba8dcf4b3ec8a066

  draft_release:
    name: Draft a release
    needs: security_hardening
    runs-on: ubuntu-latest
    steps:
    - name: Clone the repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
    - name: Draft the release
      id: release-drafter
      uses: release-drafter/release-drafter@139054aeaa9adc52ab36ddf67437541f039b88e2
      with:
        prerelease: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}